language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy: # CodeDeploy는 jar 파일을 인식하지 못하므로 기타 설정들과 압축
  - mkdir -p before-deploy # zip에 포함시킬 파일들을 담을 디렉토리
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy.
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - zip -r springboot-webservice *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/springboot-webservice.zip

deploy:
  - provicer: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: freelec-springboot-build22
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy # 해당 위치의 파일들만 s3로 전송
    wait-until-deploy: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: freelec-springboot-build22
    key: springboot-webservice.zip
    bundle_type: zip
    application: springboot-webservice # CodeDeploy application
    deployment_group: springboot-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true

notifications:
  email:
    recipients:
      - tlfanfvk@gmail.com