spring:
  session:
    store-type: jdbc
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb
    show-sql: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
      username: sa
  h2:
    console:
      enabled: true
  profiles:
    include: oauth